---
title: "IRR"
author: "S. Mason"
date: "10/3/2018"
output: html_document
---
```{r set-up, message=FALSE}
library(readxl)
library(tidyverse)
library(ggplot2)
library(irr)
library(psych)
library(gridExtra)
```

```{r import IRR data, message=FALSE}
#import the Excel sheet with the IRR data
ratings <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "IRR_2", range = cell_cols(1:10))

#Total is one reviewer and score is the other
ratings <- ratings %>% dplyr::select(Subject_ID, Reviewer, Total) %>% spread(Reviewer, Total)
colnames(ratings) <- c("Subject_ID", "Total", "score")
```

```{r add Sam's data}
sam_irr <- read_excel("~/Documents/ROCIanalysis/ROCI_sam.xlsx", sheet = "Imaging", range = cell_cols(1:16))
sam_irr <- sam_irr %>% dplyr::select(Subject_ID, Total, total_sa)
colnames(sam_irr) <- c("Subject_ID", "Total", "score")

ratings <- rbind(sam_irr, ratings)
```

```{r subset where score and total differ by more than 2}
# n = 23
differ <- ratings %>% filter(Total-score > 2 | score-Total > 2)
```

```{r how many are different?}
#69 of 172 scores were different
imgs_sam %>% filter(Total != score) %>% dplyr::select(Subject_ID, Total, score)
```

Calculating an ICC (two-way, consistency, with 95% confidence):
```{r ICC with IRR package}
irr::icc(ratings[c(2,3)], model="t", type="c", unit="s", r0=0, conf.level=0.95)
```

```{r ICC w psych package}
psych::ICC(ratings[c(2,3)], missing=TRUE, alpha=0.05)
```

<br>And a Cohen's kappa (with squared weights):
```{r kappa}
kappa2(ratings[c(2,3)], "squared")
#doesn't kappa assume nominal data??
```

<br>Scatterplot of agreement:
```{r scatterplot}
scatter <-ggplot(ratings, aes(Total, score)) + geom_jitter(size=2) + ggtitle("A") + xlab("Reviewer 1 score") + ylab("Reviewer 2 score")
scatter_lines <- scatter + geom_abline(slope=1, size=0.5, color="blue") + scale_x_continuous(breaks=seq(0,16,2)) + scale_y_continuous(breaks=seq(0,16,2)) +
  theme_minimal()
scatter_lines
```

<br>A Bland-Altman plot:
```{r BA plot}
#Generate the differences and averages for plot
ratings <- mutate(ratings, diff = (Total - score), avg = ((Total + score) / 2))
#Generate plot
BAplot <- ggplot(ratings, aes(avg, diff)) + geom_jitter(size=2) + ggtitle("B") + xlab("Average") + ylab("Difference")
BAplot_lines <- BAplot + geom_hline(yintercept=mean(ratings$diff), color="blue", size=0.5) + geom_hline(yintercept=mean(ratings$diff) - 1.96*sd(ratings$diff), color="red", size=0.5) + geom_hline(yintercept=mean(ratings$diff) + 1.96*sd(ratings$diff), color="red", size=0.5) + theme_minimal()
BAplot_lines
```

```{r plots side by side}
grid.arrange(scatter_lines, BAplot_lines, ncol=2)
```

## Comparison of Stefanie vs Sam scoring

```{r load data, echo=FALSE}
#Load data
outcomes <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "Outcomes", range = cell_cols(1:27))
imgs <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "Imaging", range = cell_cols(1:11))
med_hist <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "baseline_data", range = cell_cols(1:32))

#RWarngle data
med_hist <- med_hist %>% dplyr::select(subj_id, heart_disease___2, copd) %>% mutate(chf = as.factor(heart_disease___2), copd = as.factor(copd)) %>% dplyr::select(-heart_disease___2) %>% dplyr::rename(Subject_ID = subj_id) 

outcomes <- outcomes %>% mutate(non_white = as.factor(ifelse(Race == "White, non-Hispanic origin", 0, 1)), hosp_death = as.factor(ifelse(DC_coded == 0 | DC_coded == 1, 1, 0)), Immsupp = as.factor(Immsupp), Male = as.factor(Male)) %>% left_join(med_hist, by = "Subject_ID")

imgs <- imgs %>% dplyr::select(-day_3_cxr, -day_5_cxr) %>% filter(admit_cxr == 1) %>% left_join(outcomes, by = "Subject_ID") %>% filter(Final_Dx != "Control") 

#Numerics to factor
imgs$mort28d <- as.factor(imgs$mort28d)
imgs$mort60d <- as.factor(imgs$mort60d)
rm(outcomes)
rm(med_hist)
```


```{r load Sam's scores}
sam <- read_excel("~/Documents/ROCIanalysis/ROCI_sam.xlsx", sheet = "Imaging", range = cell_cols(1:16))
sam <- sam %>% dplyr::select(Subject_ID, total_sa)
imgs_sam <- imgs %>% left_join(sam, by = "Subject_ID") %>% mutate(score = ifelse(is.na(total_sa), Total, total_sa)) 
```

```{r in-hosp mortality, mine vs sam}
#my original
hosp_mort <- glm(hosp_death ~ Total+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs)
summary(hosp_mort)

cbind(OR = exp(coef(hosp_mort)),
      exp(confint(hosp_mort)),
      p = coef(summary(hosp_mort))[,4])

#with sam's data
hosp_mort_sam <- glm(hosp_death ~ score+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs_sam)
summary(hosp_mort_sam)

cbind(OR = exp(coef(hosp_mort_sam)),
      exp(confint(hosp_mort_sam)),
      p = coef(summary(hosp_mort_sam))[,4])
```

```{r cox regression, mine vs Sam}
refdate <- as.Date("2018-09-15")
#Create variables with survival (in days) and a binary indicating censored status
imgs <- mutate(imgs, survival = ifelse(is.na(date_death) == TRUE, as.numeric(difftime(refdate, ICU_admit, units='days')), as.numeric(difftime(date_death, ICU_admit, units='days')))) %>% mutate(censor = ifelse(is.na(date_death) == TRUE, 0, 1))

#Cox regression model
cox_all <- coxph(Surv(survival, censor) ~ Male+Age+non_white+APACHE+Immsupp+Total+copd+chf, data=imgs)
summary(cox_all)

imgs_sam <- mutate(imgs_sam, survival = ifelse(is.na(date_death) == TRUE, as.numeric(difftime(refdate, ICU_admit, units='days')), as.numeric(difftime(date_death, ICU_admit, units='days')))) %>% mutate(censor = ifelse(is.na(date_death) == TRUE, 0, 1))

#Cox regression model
cox_all_sam <- coxph(Surv(survival, censor) ~ Male+Age+non_white+APACHE+Immsupp+score+copd+chf, data=imgs_sam)
summary(cox_all_sam)
```



##NOT USED

```{r make quartiles}
#create quartiles
imgs <- imgs %>% mutate(quartile = ntile(Total,4)) 
imgs$quartile <- as.factor(imgs$quartile)
#create quartiles
imgs_sam <- imgs_sam %>% mutate(quartile = ntile(score,4)) 
imgs_sam$quartile <- as.factor(imgs_sam$quartile)
```

```{r cox by quartile}
cox_qt_base1 <- coxph(Surv(survival, censor) ~ Age+Male+Immsupp+non_white+APACHE+quartile, data=imgs)
summary(cox_qt_base1)

cox_qt_sam1 <- coxph(Surv(survival, censor) ~ Age+Male+Immsupp+non_white+APACHE+quartile, data=imgs_sam)
summary(cox_qt_sam1)
```

```{r KM on sam's data}
cox_qt_sam <- survfit(Surv(survival, censor) ~ quartile, data=imgs_sam)

plot_all_sam <- ggsurvplot(cox_qt_sam, data=imgs_sam, pval=TRUE, pval.size=3,
           ggtheme = theme_minimal(), legend.title="Quartile", legend.labs=c("Q1","Q2","Q3","Q4"),
           risk.table=TRUE, tables.height = 0.2, tables.theme = theme_cleantable(),
           xlim=c(0,3650), break.time.by=365.25, xscale="d_m", ylab="",
           xlab="Months", font.legend=8, title="Entire cohort", font.title=10,
           legend=c(1.1,0.6), risk.table.y.text=FALSE,
           risk.table.fontsize=3, risk.table.title="") 
plot_all_sam$plot <- plot_all_sam$plot + theme(plot.title = element_text(hjust = 0.5))
plot_all_sam
```

```{r Stef Sam IRR}
sam_irr <- read_excel("~/Documents/ROCIanalysis/ROCI_sam.xlsx", sheet = "Imaging", range = cell_cols(1:16))
sam_irr <- sam_irr %>% dplyr::select(Subject_ID, Total, total_sa)

irr::icc(sam_irr[c(2,3)], model="t", type="c", unit="s", r0=0, conf.level=0.95)
```

## Isolating CXR read by Stefanie
```{r xrays for Sam}
temp_data <- read_excel("~/Documents/ROCIanalysis/ROCI_temp.xlsx", sheet = "Img_edit") #previously scored
temp_imgs <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "Imaging", range = cell_cols(1:11)) #final group
```
```{r}
subjects <- imgs$Subject_ID
temp_data <- temp_data %>% filter(Subject_ID %in% subjects)
temp_imgs <- temp_imgs %>% dplyr::select(-day_3_cxr, -day_5_cxr) %>% filter(admit_cxr == 1) %>% filter(Subject_ID %in% subjects)
```
```{r}
temp_merged <- merge(x=temp_data, y=temp_imgs, by.x=c("Subject_ID", "CXRdate"), by.y=c("Subject_ID", "cxr_date"))
```
```{r}
temp_merged %>% filter(Total.x != Total.y)
```

```{r}
write.csv(temp_merged, file="Temp_merged.csv", row.names=FALSE)
```



