---
title: "Working ROCI analysis"
author: "S. Mason"
output: pdf_document
---

```{r setup, echo=FALSE, message=FALSE}
library(readxl)
library(dplyr)
library(ggplot2)
library(survival)
library(survminer)
library(QuantPsyc)
library(gridExtra)
library(clinfun)
knitr::opts_chunk$set(message = FALSE)
```

```{r load data, echo=FALSE}
#Load data
outcomes <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "Outcomes", range = cell_cols(1:27))
imgs <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "Imaging", range = cell_cols(1:11))
med_hist <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "baseline_data", range = cell_cols(1:32))
```
```{r more prep}
#RWarngle data
med_hist <- med_hist %>% dplyr::select(subj_id, heart_disease___2, copd) %>% rename(Subject_ID = subj_id) %>% mutate(chf = as.factor(heart_disease___2), copd = as.factor(copd)) %>% dplyr::select(-heart_disease___2)

outcomes <- outcomes %>% mutate(non_white = as.factor(ifelse(Race == "White, non-Hispanic origin", 0, 1)), hosp_death = as.factor(ifelse(DC_coded == 0 | DC_coded == 1, 1, 0)), Immsupp = as.factor(Immsupp), Male = as.factor(Male)) %>% left_join(med_hist, by = "Subject_ID")

imgs <- imgs %>% dplyr::select(-day_3_cxr, -day_5_cxr) %>% filter(admit_cxr == 1) %>% left_join(outcomes, by = "Subject_ID") %>% filter(Final_Dx != "Control") 

#Numerics to factor
imgs$mort28d <- as.factor(imgs$mort28d)
imgs$mort60d <- as.factor(imgs$mort60d)
rm(outcomes)
rm(med_hist)
```


```{r fun w functions, echo=FALSE}
#Function to compare means 

my_stat_compare_means  <- function (mapping = NULL, data = NULL, method = NULL, paired = FALSE,
                                    method.args = list(), ref.group = NULL, comparisons = NULL,
                                    hide.ns = FALSE, label.sep = ", ", label = NULL, label.x.npc = "left",
                                    label.y.npc = "top", label.x = NULL, label.y = NULL, tip.length = 0.03,
                                    symnum.args = list(), geom = "text", position = "identity",
                                    na.rm = FALSE, show.legend = NA, inherit.aes = TRUE, ...)
{
  if (!is.null(comparisons)) {
    method.info <- ggpubr:::.method_info(method)
    method <- method.info$method
    method.args <- ggpubr:::.add_item(method.args, paired = paired)
    if (method == "wilcox.test")
      method.args$exact <- FALSE
    pms <- list(...)
    size <- ifelse(is.null(pms$size), 0.3, pms$size)
    color <- ifelse(is.null(pms$color), "black", pms$color)
    map_signif_level <- FALSE
    if (is.null(label))
      label <- "p.format"
    if (ggpubr:::.is_p.signif_in_mapping(mapping) | (label %in% "p.signif")) {
      if (ggpubr:::.is_empty(symnum.args)) {
        map_signif_level <- c(`****` = 1e-04, `***` = 0.001,
                              `**` = 0.01, `*` = 0.05, ns = 1)
      } else {
        map_signif_level <- symnum.args
      }
      if (hide.ns)
        names(map_signif_level)[5] <- " "
    }
    step_increase <- ifelse(is.null(label.y), 0.12, 0)
    ggsignif::geom_signif(comparisons = comparisons, y_position = label.y,
                          test = method, test.args = method.args, step_increase = step_increase,
                          size = size, color = color, map_signif_level = map_signif_level,
                          tip_length = tip.length, data = data)
  } else {
    mapping <- ggpubr:::.update_mapping(mapping, label)
    layer(stat = StatCompareMeans, data = data, mapping = mapping,
          geom = geom, position = position, show.legend = show.legend,
          inherit.aes = inherit.aes, params = list(label.x.npc = label.x.npc,
                                                   label.y.npc = label.y.npc, label.x = label.x,
                                                   label.y = label.y, label.sep = label.sep, method = method,
                                                   method.args = method.args, paired = paired, ref.group = ref.group,
                                                   symnum.args = symnum.args, hide.ns = hide.ns,
                                                   na.rm = na.rm, ...))
  }
}
```

```{r create surivival data}
refdate <- as.Date("2018-09-15")
#Create variables with survival (in days) and a binary indicating censored status
imgs <- mutate(imgs, survival = ifelse(is.na(date_death) == TRUE, as.numeric(difftime(refdate, ICU_admit, units='days')), as.numeric(difftime(date_death, ICU_admit, units='days')))) %>% mutate(censor = ifelse(is.na(date_death) == TRUE, 0, 1))
```


#In-hospital Mortality
##Logistic Regression

```{r logit in-hospital mortality, warning=FALSE}
#In-hospital mortality
hosp_mort <- glm(hosp_death ~ Total+Male+Age+Immsupp+APACHE+non_white, family=binomial(link='logit'), data=imgs)
summary(hosp_mort)

cbind(OR = exp(coef(hosp_mort)),
      exp(confint(hosp_mort)),
      p = coef(summary(hosp_mort))[,4])
```

```{r in hosp controlling for copd/chf}
#In-hospital mortality, entire cohort
hosp_mort_phx <- glm(hosp_death ~ Total+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs)
summary(hosp_mort)

cbind(OR = exp(coef(hosp_mort_phx)),
      exp(confint(hosp_mort_phx)),
      p = coef(summary(hosp_mort_phx))[,4])
```

```{r in-hosp non-ARDS}
imgs_non <- imgs %>% filter(Final_Dx != "ARDS" & Final_Dx != "Sepsis/ARDS") %>% mutate(quartile = as.factor(ntile(Total,4)))

hosp_mort_non <- glm(hosp_death ~ Total+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs_non)
summary(hosp_mort_non)

cbind(OR = exp(coef(hosp_mort_non)),
      exp(confint(hosp_mort_non)),
      p = coef(summary(hosp_mort_non))[,4])
```

```{r in hosp ARDS only}
imgs_ards <- imgs %>% filter(Final_Dx == "ARDS" | Final_Dx == "Sepsis/ARDS") %>% mutate(quartile = as.factor(ntile(Total,4)))

hosp_mort_ards <- glm(hosp_death ~ Total+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs_ards)
summary(hosp_mort_ards)

cbind(OR = exp(coef(hosp_mort_ards)),
      exp(confint(hosp_mort_ards)),
      p = coef(summary(hosp_mort_ards))[,4])

```


#28-day and 60-day mortality
##Logistic Regression

```{r logit 28d mortality}
one_month <- glm(mort28d ~ Total+Male+Age+Immsupp+APACHE+non_white, family=binomial(link='logit'), data=imgs)
summary(one_month)

cbind(OR = exp(coef(one_month)),
      exp(confint(one_month)),
      p = coef(summary(one_month))[,4])
```

```{r logit 60d mortality}
two_month <- glm(mort60d ~ Total+Male+Age+Immsupp+APACHE+non_white, family=binomial(link='logit'), data=imgs)
summary(two_month)

cbind(OR = exp(coef(two_month)),
      exp(confint(two_month)),
      p = coef(summary(two_month))[,4])

imgs %>% filter(mort60d == 1) %>% summarize(count = length(Total))
```

#Overall Mortality
##Cox regression of entire cohort (not in quartiles)

```{r cox proportional hazards}
#Cox regression model
cox_all <- coxph(Surv(survival, censor) ~ Male+Age+non_white+APACHE+Immsupp+Total, data=imgs)
summary(cox_all)
```
```{r controlling for copd/chf}
cox_all_phx <- coxph(Surv(survival, censor) ~ Male+Age+non_white+APACHE+Immsupp+Total+copd+chf, data=imgs)
summary(cox_all_phx)
```

```{r overall mortality in ARDS only}
cox_ards <- coxph(Surv(survival, censor) ~ Male+Age+non_white+APACHE+Immsupp+Total+copd+chf, data=imgs_ards)
summary(cox_ards)

cox_ards_qt <- coxph(Surv(survival, censor) ~ Male+Age+non_white+APACHE+Immsupp+quartile+copd+chf, data=imgs_ards)
summary(cox_ards_qt)
```


```{r test PH assumption}
schoenfeld_res <- cox.zph(cox_all)
plot(schoenfeld_res)
```

##Cox regression of entire cohort by quartile
```{r quartiles}
#create quartiles
imgs <- imgs %>% mutate(quartile = ntile(Total,4)) 
imgs$quartile <- as.factor(imgs$quartile)
```
```{r cox all subjects by quartiles}
#Cox regressions
cox_qt <- survfit(Surv(survival, censor) ~ quartile, data=imgs) #for graph
cox_qt

#cox_quart <- coxph(Surv(survival, censor) ~ Age+Male+Immsupp+non_white+APACHE+quartile, data=imgs) #for betas
#summary(cox_quart)
```

```{r Cox quartiles for ARDS only}
cox_ards_q <- coxph(Surv(survival, censor) ~ Male+Age+non_white+APACHE+Immsupp+quartile, data=imgs_ards)
summary(cox_ards_q)

cox_ards_qp <- survfit(Surv(survival, censor) ~ quartile, data=imgs_ards)

plot_ards <- ggsurvplot(cox_ards_qp, data=imgs_ards, pval=TRUE, pval.size=3,
           ggtheme = theme_minimal(), legend.title="Quartile", legend.labs=c("Q1","Q2","Q3","Q4"),
           risk.table=TRUE, tables.height = 0.2, tables.theme = theme_cleantable(),
           xlim=c(0,3650), break.time.by=365.25, xscale="d_m", ylab="",
           xlab="Months", font.legend=8, title="Entire cohort", font.title=10,
           legend=c(1.1,0.6), risk.table.y.text=FALSE,
           risk.table.fontsize=3, risk.table.title="") 
plot_ards$plot <- plot_ards$plot + theme(plot.title = element_text(hjust = 0.5))
plot_ards
```


```{r pairwise quartile for Cox}
#Adding copd/chf did not explode the std errors. 

contrasts(imgs$quartile) <- contr.treatment(4, base=4)
cox_qt_base4 <- coxph(Surv(survival, censor) ~ Age+Male+Immsupp+non_white+APACHE+copd+chf+quartile, data=imgs)
summary(cox_qt_base4)
#Result: Only Q1 is significant

contrasts(imgs$quartile) <- contr.treatment(4, base=3)
cox_qt_base3 <- coxph(Surv(survival, censor) ~ Age+Male+Immsupp+non_white+APACHE+copd+chf+quartile, data=imgs)
summary(cox_qt_base3)
#Result: Only Q1 is significant

contrasts(imgs$quartile) <- contr.treatment(4, base=2)
cox_qt_base2 <- coxph(Surv(survival, censor) ~ Age+Male+Immsupp+non_white+APACHE+copd+chf+quartile, data=imgs)
summary(cox_qt_base2)
#Result: Only Q1 is significant

#reset factor to base 1
contrasts(imgs$quartile) <- contr.treatment(4, base=1)
cox_qt_base1 <- coxph(Surv(survival, censor) ~ Age+Male+Immsupp+non_white+APACHE+copd+chf+quartile, data=imgs)
summary(cox_qt_base1)
```

```{r Kaplan Meier all subjects}
plot_all <- ggsurvplot(cox_qt, data=imgs, pval=TRUE, pval.size=3,
           ggtheme = theme_minimal(), legend.title="Quartile", legend.labs=c("Q1","Q2","Q3","Q4"),
           risk.table=TRUE, tables.height = 0.2, tables.theme = theme_cleantable(),
           xlim=c(0,3650), break.time.by=365.25, xscale="d_m", ylab="",
           xlab="Months", font.legend=8, title="Entire cohort", font.title=10,
           legend=c(1.1,0.6), risk.table.y.text=FALSE,
           risk.table.fontsize=3, risk.table.title="") 
plot_all$plot <- plot_all$plot + theme(plot.title = element_text(hjust = 0.5))
plot_all
```


##Cox regression for non-ARDS subset
```{r Cox regression for non ARDS}
#non-ARDS patients
imgs_non <- imgs %>% filter(Final_Dx != "ARDS" & Final_Dx != "Sepsis/ARDS") %>% mutate(quartile = as.factor(ntile(Total,4)))
```
```{r}
cox_all_non <- coxph(Surv(survival, censor) ~ Age+Male+Immsupp+non_white+APACHE+copd+chf+Total, data=imgs_non) #for betas
summary(cox_all_non)
#std errors checked -> ok

cox_all_non_strata <- survfit(Surv(survival, censor) ~ quartile, data = imgs_non) #for KM
```
```{r Cox pairwise quartile non ARDS}
#std errors checked ->okay

contrasts(imgs_non$quartile) <- contr.treatment(4, base=4)
cox_non_base4 <- coxph(Surv(survival, censor) ~ Age+Male+Immsupp+non_white+APACHE+copd+chf+quartile, data=imgs_non)
summary(cox_non_base4)
#Result: Only Q1 is significant

contrasts(imgs_non$quartile) <- contr.treatment(4, base=3)
cox_non_base3 <- coxph(Surv(survival, censor) ~ Age+Male+Immsupp+non_white+APACHE+copd+chf+quartile, data=imgs_non)
summary(cox_non_base3)
#Result: Only Q1 is significant

contrasts(imgs_non$quartile) <- contr.treatment(4, base=2)
cox_non_base2 <- coxph(Surv(survival, censor) ~ Age+Male+Immsupp+non_white+APACHE+copd+chf+quartile, data=imgs_non)
summary(cox_non_base2)
#Result: Only Q1 is significant

#reset factor to base 1
contrasts(imgs_non$quartile) <- contr.treatment(4, base=1)
cox_non_base1 <- coxph(Surv(survival, censor) ~ Age+Male+Immsupp+non_white+APACHE+copd+chf+quartile, data=imgs_non)
summary(cox_non_base1)

```

```{r KM for non ARDS}
plot_non <- ggsurvplot(cox_all_non_strata, data=imgs_non, pval=TRUE, pval.size=3,
           ggtheme = theme_minimal(), legend.title="Quartile", 
           risk.table=TRUE, tables.height = 0.2, tables.theme = theme_cleantable(),
           xlim=c(0,3650), break.time.by=365.25, xscale="d_m", ylab="",
           xlab="Months", font.legend=8, title="Non-ARDS patients", font.title=10,
           legend="none", risk.table.y.text=FALSE, 
           risk.table.fontsize=3, risk.table.title="") 
plot_non$plot <- plot_non$plot + theme(axis.text.y = element_blank(), plot.title = element_text(hjust = 0.5))
plot_non
```

##KM curves side by side
```{r arrange the plots}
KM_curves <- list()
KM_curves[[1]] <- plot_all
KM_curves[[2]] <- plot_non
arrange_ggsurvplots(KM_curves, print=TRUE, ncol=2, nrow=1)
```

```{r in-hosp mort by quartile}
#std errors checked ->okay
hosp_mort <- glm(hosp_death ~ quartile+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs)
summary(hosp_mort)

cbind(OR = exp(coef(hosp_mort)),
      exp(confint(hosp_mort)),
      p = coef(summary(hosp_mort))[,4])
```

```{r pairwise in-hosp quartile evaluation, message=FALSE}
contrasts(imgs$quartile) <- contr.treatment(4, base=2)
inhosp_quart_base2 <- glm(hosp_death ~ quartile+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs)
summary(inhosp_quart_base2)
#result: Q1is significant, 3 and 4 are not

cbind(OR = exp(coef(inhosp_quart_base2)),
      exp(confint(inhosp_quart_base2)),
      p = coef(summary(inhosp_quart_base2))[,4])

contrasts(imgs$quartile) <- contr.treatment(4, base=3)
inhosp_quart_base3 <- glm(hosp_death ~ quartile+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs)
summary(inhosp_quart_base3)
#result: Q1 is significant, 2 and 4 are not

cbind(OR = exp(coef(inhosp_quart_base3)),
      exp(confint(inhosp_quart_base3)),
      p = coef(summary(inhosp_quart_base3))[,4])

contrasts(imgs$quartile) <- contr.treatment(4, base=4)
inhosp_quart_base4 <- glm(hosp_death ~ quartile+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs)
summary(inhosp_quart_base4)
#result: Q1 is significant, 2 and 3 are not

cbind(OR = exp(coef(inhosp_quart_base4)),
      exp(confint(inhosp_quart_base4)),
      p = coef(summary(inhosp_quart_base4))[,4])

#reset factor to base 1
contrasts(imgs$quartile) <- contr.treatment(4, base=1)
```

```{r non-ARDS in hospital mortality}
#std errors checked ->okay

hosp_mort_non_r1 <- glm(hosp_death ~ quartile+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs_non)
summary(hosp_mort_non_r1)

cbind(OR = exp(coef(hosp_mort_non_r1)),
      exp(confint(hosp_mort_non_r1)),
      p = coef(summary(hosp_mort_non_r1))[,4])
```
```{r}
#ref level =2
contrasts(imgs_non$quartile) <- contr.treatment(4, base = 2)
hosp_mort_non_r2 <- glm(hosp_death ~ quartile+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs_non)
summary(hosp_mort_non_r2)

cbind(OR = exp(coef(hosp_mort_non_r2)),
      exp(confint(hosp_mort_non_r2)),
      p = coef(summary(hosp_mort_non_r2))[,4])

#ref level = 3
contrasts(imgs_non$quartile) <- contr.treatment(4, base = 3)
hosp_mort_non_r3 <- glm(hosp_death ~ quartile+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs_non)
summary(hosp_mort_non_r3)

cbind(OR = exp(coef(hosp_mort_non_r3)),
      exp(confint(hosp_mort_non_r3)),
      p = coef(summary(hosp_mort_non_r3))[,4])

#ref level = 4
contrasts(imgs_non$quartile) <- contr.treatment(4, base = 4)
hosp_mort_non_r4 <- glm(hosp_death ~ quartile+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs_non)
summary(hosp_mort_non_r4)

cbind(OR = exp(coef(hosp_mort_non_r4)),
      exp(confint(hosp_mort_non_r4)),
      p = coef(summary(hosp_mort_non_r4))[,4])

#reset ref level to 1
contrasts(imgs_non$quartile) <- contr.treatment(4, base = 1)
```


##ICU Length of stay
```{r ICU LOS, warning=FALSE}
contrasts(imgs$quartile) <-contr.treatment(4,base = 1)

#Negative binomial model
#std errors checked -> okay

ICUdays_nb <- glm.nb(ICU_days ~ Total+APACHE+Age+non_white+Male+Immsupp+copd+chf, data=imgs)
summary(ICUdays_nb)
cbind(IRR = exp(coef(ICUdays_nb)), exp(confint(ICUdays_nb)))[2,]
```

```{r ICU LOS pairwise quartile}
#standard errors checked -> okay
#Base = 1
contrasts(imgs$quartile) <-contr.treatment(4,base = 1)
ICUdays_nb_q1 <- glm.nb(ICU_days ~ quartile+APACHE+Age+non_white+Male+Immsupp+copd+chf, data=imgs)
summary(ICUdays_nb_q1)

cbind(IRR = exp(coef(ICUdays_nb_q1)),
      exp(confint(ICUdays_nb_q1)),
      p = coef(summary(ICUdays_nb_q1))[,4])

#Base = 2
contrasts(imgs$quartile) <-contr.treatment(4,base = 2)
ICUdays_nb_q2 <- glm.nb(ICU_days ~ quartile+APACHE+Age+non_white+Male+Immsupp+copd+chf, data=imgs)
summary(ICUdays_nb_q2)

cbind(IRR = exp(coef(ICUdays_nb_q2)),
      exp(confint(ICUdays_nb_q2)),
      p = coef(summary(ICUdays_nb_q2))[,4])

#Base = 3
contrasts(imgs$quartile) <-contr.treatment(4,base = 3)
ICUdays_nb_q3 <- glm.nb(ICU_days ~ quartile+APACHE+Age+non_white+Male+Immsupp+copd+chf, data=imgs)
summary(ICUdays_nb_q3)

cbind(IRR = exp(coef(ICUdays_nb_q3)),
      exp(confint(ICUdays_nb_q3)),
      p = coef(summary(ICUdays_nb_q3))[,4])

#Base = 4
contrasts(imgs$quartile) <-contr.treatment(4,base = 4)
ICUdays_nb_q4 <- glm.nb(ICU_days ~ quartile+APACHE+Age+non_white+Male+Immsupp+copd+chf, data=imgs)
summary(ICUdays_nb_q4)

cbind(IRR = exp(coef(ICUdays_nb_q4)),
      exp(confint(ICUdays_nb_q4)),
      p = coef(summary(ICUdays_nb_q4))[,4])

#Reset base level
contrasts(imgs$quartile) <-contr.treatment(4,base = 1)
```


##Duration of mechanical ventilation
```{r mechanical ventilation, warning=FALSE}
#make the subset of data: only intubated patients (n = 286)
intub <- imgs %>% filter(days_MV != 0)
```

```{r neg binomial for days MV}
#standard errors checked ->okay
MVdays_nb2 <- glm.nb(days_MV ~ Total+APACHE+Age+non_white+Male+Immsupp+copd+chf, data=intub)
summary(MVdays_nb2)
cbind(IRR = exp(coef(MVdays_nb2)), exp(confint(MVdays_nb2)))[2,]
```

```{r quartile}
#Standard errors checked -> okay
MVdays_nbq <- glm.nb(days_MV ~ quartile+APACHE+Age+non_white+Male+Immsupp+copd+chf, data=intub)
summary(MVdays_nbq)
#cbind(IRR = exp(coef(MVdays_nbq)), exp(confint(MVdays_nbq)))[2:4,]
```

```{r duration MV pairwaise quartile}
#Base = 1
contrasts(intub$quartile) <-contr.treatment(4,base = 1)
MVdays_nb2_q1 <- glm.nb(days_MV ~ quartile+APACHE+Age+non_white+Male+Immsupp+copd+chf, data=intub)
summary(MVdays_nb2_q1)

cbind(IRR = exp(coef(MVdays_nb2_q1)),
      exp(confint(MVdays_nb2_q1)),
      p = coef(summary(MVdays_nb2_q1))[,4])

#Base = 2
contrasts(intub$quartile) <-contr.treatment(4,base = 2)
MVdays_nb2_q2 <- glm.nb(days_MV ~ quartile+APACHE+Age+non_white+Male+Immsupp+copd+chf, data=intub)
summary(MVdays_nb2_q2)

cbind(IRR = exp(coef(MVdays_nb2_q2)),
      exp(confint(MVdays_nb2_q2)),
      p = coef(summary(MVdays_nb2_q2))[,4])

#Base = 3
contrasts(intub$quartile) <-contr.treatment(4,base = 3)
MVdays_nb2_q3 <- glm.nb(days_MV ~ quartile+APACHE+Age+non_white+Male+Immsupp+copd+chf, data=intub)
summary(MVdays_nb2_q3)

cbind(IRR = exp(coef(MVdays_nb2_q3)),
      exp(confint(MVdays_nb2_q3)),
      p = coef(summary(MVdays_nb2_q3))[,4])

#Base = 4
contrasts(intub$quartile) <-contr.treatment(4,base = 4)
MVdays_nb2_q4 <- glm.nb(days_MV ~ quartile+APACHE+Age+non_white+Male+Immsupp+copd+chf, data=intub)
summary(MVdays_nb2_q4)

cbind(IRR = exp(coef(MVdays_nb2_q4)),
      exp(confint(MVdays_nb2_q4)),
      p = coef(summary(MVdays_nb2_q4))[,4])

#Reset base level
contrasts(intub$quartile) <-contr.treatment(4,base = 1)
```


```{r IRR to absolute days}
#ICU days (mean x IRR)
incr_days = (1.058129 * mean(imgs$ICU_days)) - mean(imgs$ICU_days)
incr_days
median(imgs$ICU_days)

#Days MV
more_days = (1.045064 * mean(intub$days_MV)) - mean(intub$days_MV)
more_days
median(intub$days_MV)

```


```{r boxplot data prep}
library(reshape2)
library(RColorBrewer)
#Eliminate non-intubated from the MV data and transform for plotting
meltICU <- imgs %>% dplyr::select(Subject_ID, ICU_days, quartile) %>% melt(id.vars="quartile", measure.vars="ICU_days")
meltMV <- imgs %>% filter(days_MV != 0) %>% dplyr::select(Subject_ID, days_MV, quartile) %>% melt(id.vars="quartile", measure.vars="days_MV")
meltplot <- rbind(meltICU, meltMV)
```

```{r}
ICUdata <- imgs %>% dplyr::select(Subject_ID, ICU_days, quartile) %>% rename(value = ICU_days) %>% mutate(variable = "ICU_days")
MVdata <- intub %>% dplyr::select(Subject_ID, days_MV, quartile) %>% rename(value = days_MV) %>% mutate(variable = "days_MV")
meltplot <- rbind(ICUdata, MVdata)
```


```{r boxplot: options}
#Boxplot square root scale
ggplot(meltplot) + geom_boxplot(aes(quartile, sqrt(value), color=variable)) +   
  scale_x_discrete(name="Chest Radiograph Score Quartile") + 
  scale_y_continuous(name="(Square root of) Days") +
  theme_minimal() + theme(plot.title = element_text(face = "bold")) +
  theme(panel.grid.minor = element_blank()) + 
  theme(legend.title = element_blank()) +
  theme(legend.position = "bottom") +
  scale_color_discrete(labels=c("Length of stay", "Ventilator days"))

#Boxplot log scale
ggplot(meltplot) + geom_boxplot(aes(quartile, log(value), color=variable)) +   
  scale_x_discrete(name="Chest Radiograph Score Quartile") + 
  scale_y_continuous(name="(Log of) Days", limits=c(0,5)) +
  theme_minimal() + theme(plot.title = element_text(face = "bold")) +
  theme(panel.grid.minor = element_blank()) + 
  theme(legend.title = element_blank()) +
  theme(legend.position = "bottom") +
  scale_color_discrete(labels=c("Length of stay", "Ventilator days"))

```

```{r boxplot with stats}
box_comparisons <- list(c("1","2"), c("2","3"), c("3","4"), c("1","3"), c("1","4"),  c("2","4"))

symnum.args <- c("***"=0.05,ns=1)

var_names <- c('ICU_days' = "Length of ICU stay", 'days_MV' = "Ventilator days")

my_boxplot <- ggplot(meltplot, aes(quartile, log(value))) + geom_boxplot() + 
  facet_grid(.~ variable, labeller=as_labeller(var_names)) +
  my_stat_compare_means(label = "p.signif", method = "t.test", comparisons = box_comparisons, symnum.args = symnum.args) +
  scale_x_discrete(name="Chest Radiograph Score Quartile") +
  scale_y_continuous(name="Days", limits=c(-0.25,7.5)) +
  theme_bw() +
  annotate("text", x=2.5, y=-0.2, label="p for trend < .001")

ggsave("boxplots.tiff", unit="cm", width=9, height=6.4, dpi=600, compression='lzw')

my_boxplot 
```

```{r boxplot with stats, non-transformed data}
box_comparisons <- list(c("1","2"), c("2","3"), c("3","4"), c("1","3"), c("1","4"),  c("2","4"))

symnum.args <- c("***"=0.05,ns=1)

var_names <- c('ICU_days' = "Length of ICU stay", 'days_MV' = "Ventilator days")

my_boxplot <- ggplot(meltplot, aes(quartile, value)) + geom_boxplot() + 
  facet_grid(.~ variable, labeller=as_labeller(var_names)) +
  my_stat_compare_means(label = "p.signif", method = "t.test", comparisons = box_comparisons, symnum.args = symnum.args) +
  scale_x_discrete(name="Chest Radiograph Score Quartile") +
  scale_y_log10(name="Days") +
  theme_bw() +
  annotate("text", x=2.5, y=-0.2, label="p for trend < .001")

ggsave("boxplots.tiff", unit="cm", width=9, height=6.4, dpi=600, compression='lzw')

my_boxplot 
```

```{r}
wilcox_data <- meltplot %>% filter(variable == "days_MV") %>% filter(quartile == 2 | quartile == 3)
t.test(log(wilcox_data$value) ~ wilcox_data$quartile)
```


```{r trend test}
# jonkheere Terpstra test
ICUdata$quartile <- ordered(ICUdata$quartile, levels=c("1", "2", "3", "4"))
jonckheere.test(ICUdata$value, ICUdata$quartile, alternative="two.sided")

MVdata$quartile <- ordered(MVdata$quartile, levels=c("1", "2", "3", "4"))
jonckheere.test(MVdata$value, MVdata$quartile, alternative="two.sided")
```


##Miscellaneous

```{r survival stats}
shapiro.test(imgs$survival)

imgs %>% summarize(mean = mean(survival), median = median(survival), min = min(survival), max = max(survival), count = length(survival))

imgs %>% mutate(surv_quart = ntile(survival, 4)) %>% group_by(surv_quart) %>% summarize(mean = mean(survival), median = median(survival), min = min(survival), max = max(survival), count = length(survival))
```

```{r case mix}
imgs %>% group_by(Final_Dx) %>% summarize(count = length(Total))
```

```{r distribution of CXR scores}
imgs %>% ggplot(aes(Total, fill = quartile)) + geom_histogram(bins = 15)

imgs %>% summarize( median = median(Total), mean = mean(Total))
imgs %>% group_by(quartile) %>% summarize(min = min(Total), max = max(Total))
```

```{r recheck tbl 1}
imgs %>% summarize(med_age = median(Age), med_apa = median(APACHE))
imgs %>% group_by(Male) %>% summarize(count = length(Total))
imgs %>% group_by(non_white) %>% summarize(count = length(Total))
imgs %>% group_by(Immsupp) %>% summarize(count = length(Total))

imgs %>% mutate(age_qt = ntile(Age,4)) %>% group_by(age_qt) %>% summarize(lower = min(Age), upper = max(Age))
imgs %>% mutate(apa_qt = ntile(APACHE,4)) %>% group_by(apa_qt) %>% summarize(lower = min(APACHE), upper = max(APACHE))
```

```{r event rates}
imgs %>% filter(!is.na(date_death)) %>% summarize(count = length(Total)) #total death events in cohort (Cox event rate)
imgs %>% filter(DC_coded == 0 | DC_coded == 1) %>% summarize(count = length(Total)) #in hospital deaths - entire cohort
imgs_non %>% filter(DC_coded == 0 | DC_coded == 1) %>% summarize(count = length(Total)) # in hospital deaths for ARDS only
```

```{r pulling the MRNs of subjects in order to obtain CXR}
key <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "Key", range = cell_cols(1:2))
subjects <- key %>% filter(Subject_ID %in% imgs$Subject_ID)
subjects <- imgs %>% dplyr::select(Subject_ID, cxr_date, Hosp_dc) %>% right_join(subjects)
write.csv(subjects, file="subjects.csv", row.names = FALSE)
```

```{r correlation btw CXR & APACHE}
#CXR scores are non-normally distributed and ordinal, will use a spearman correlation.

imgs %>% dplyr::select(Total, APACHE) %>% cor(., use = "pairwise.complete.obs", method="spearman")

cor.test(imgs$Total, imgs$APACHE, method="spearman", alternative = "t")
```
```{r mortality vs CXR score scatterplot}
imgs %>% ggplot(aes(Subject_ID, Total, color=hosp_death)) + geom_jitter() + scale_color_manual(values=c("black", "red"))
```
```{r mortality vs CXR score boxplot}
imgs %>% ggplot(aes(quartile, Total, color=hosp_death)) + geom_jitter() + scale_color_manual(values=c("black", "red"))
```
```{r mortality by CXR score histogram}
imgs %>% ggplot(aes(Total, fill = hosp_death)) + geom_histogram() + scale_fill_manual(values=c("black", "red"))
```


