---
title: "ROC"
author: "Stefanie"
date: "8/20/2019"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE}
library(readxl)
library(dplyr)
library(ggplot2)
library(survival)
library(survminer)
library(QuantPsyc)
library(gridExtra)
library(clinfun)
library(generalhoslem)
library(pROC)

knitr::opts_chunk$set(message = FALSE)
```


```{r load data, echo=FALSE}
#Load data
outcomes <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "Outcomes", range = cell_cols(1:27))
imgs <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "Imaging", range = cell_cols(1:11))
med_hist <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "baseline_data", range = cell_cols(1:32))
```

```{r more prep}
#RWarngle data
med_hist <- med_hist %>% dplyr::select(subj_id, heart_disease___2, copd) %>% mutate(chf = as.factor(heart_disease___2), copd = as.factor(copd)) %>% dplyr::select(-heart_disease___2) %>% dplyr::rename(Subject_ID = subj_id) 

outcomes <- outcomes %>% mutate(non_white = as.factor(ifelse(Race == "White, non-Hispanic origin", 0, 1)), hosp_death = as.factor(ifelse(DC_coded == 0 | DC_coded == 1, 1, 0)), Immsupp = as.factor(Immsupp), Male = as.factor(Male)) %>% left_join(med_hist, by = "Subject_ID")

imgs <- imgs %>% dplyr::select(-day_3_cxr, -day_5_cxr) %>% filter(admit_cxr == 1) %>% left_join(outcomes, by = "Subject_ID") %>% filter(Final_Dx != "Control") 

#Numerics to factor
imgs$mort28d <- as.factor(imgs$mort28d)
imgs$mort60d <- as.factor(imgs$mort60d)
rm(outcomes)
rm(med_hist)
```

```{r create surivival data}
refdate <- as.Date("2018-09-15")
#Create variables with survival (in days) and a binary indicating censored status
imgs <- mutate(imgs, survival = ifelse(is.na(date_death) == TRUE, as.numeric(difftime(refdate, ICU_admit, units='days')), as.numeric(difftime(date_death, ICU_admit, units='days')))) %>% mutate(censor = ifelse(is.na(date_death) == TRUE, 0, 1))
```

```{r create quartiles}
#create quartiles
imgs <- imgs %>% mutate(quartile = ntile(Total,4)) 
imgs$quartile <- as.factor(imgs$quartile)
```

##Looking at calibration and discrimination

```{r in hosp controlling for copd/chf}
#In-hospital mortality, entire cohort
hosp_mort_phx <- glm(hosp_death ~ Total+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs)
summary(hosp_mort_phx)

cbind(OR = exp(coef(hosp_mort_phx)),
      exp(confint(hosp_mort_phx)),
      p = coef(summary(hosp_mort_phx))[,4])
```

```{r Hosmer Lemeshow}
HLtest <- logitgof(imgs$hosp_death, fitted(hosp_mort_phx), g=10)
HLtest
```

```{r what does one curve look like?}
mort_cxr <- glm(hosp_death ~ Total, family=binomial(link = 'logit'), data=imgs)
pred_cxr <- predict(mort_cxr, type=c("response"))
roccurve <- roc(imgs$hosp_death ~ pred_cxr)
ggroc(roccurve, color="darkorange") + theme_linedraw()

```

```{r calibration: multiple curves: SOFA score}
#Univariate CXR score
mort_cxr <- glm(hosp_death ~ Total, family=binomial(link = 'logit'), data=imgs)
pred_cxr <- predict(mort_cxr, type=c("response"))
roccurve <- roc(imgs$hosp_death ~ pred_cxr)
#roc <- ggroc(roccurve, color="royalblue") 
auc(roccurve)

#Univaraite SOFA
mort_sofa <- glm(hosp_death ~ SOFA, family=binomial(link = 'logit'), data=imgs)
pred_sofa <- predict(mort_sofa, type=c("response"))
roccurve2 <- roc(imgs$hosp_death ~ pred_sofa)
#roc2 <- ggroc(roccurve2, color="darkorange")
auc(roccurve2)

#CXR + SOFA
mort_cxr_sofa <- glm(hosp_death ~ Total+SOFA, family=binomial(link = 'logit'), data=imgs)
pred_cxr_sofa <- predict(mort_cxr_sofa, type=c("response"))
roccurve3 <- roc(imgs$hosp_death ~ pred_cxr_sofa)
#roc3 <- ggroc(roccurve3, color="maroon")
auc(roccurve3)


sofa_plot <- ggroc(list(CXR=roccurve, SOFA=roccurve2, CXRSOFA=roccurve3), legacy.axes = T) + 
  theme_linedraw() + 
  geom_segment(aes(x=0,xend=1,y=0,yend=1), color="lightgray", linetype="dashed") +
  scale_color_manual(values=c("royalblue", "darkorange", "maroon"), labels=c("CXR (AUC 0.64)", "SOFA (AUC 0.62)", "CXR+SOFA (AUC 0.69)")) +
  theme(legend.title = element_blank()) + theme(legend.position = c(0.7,0.2)) 

sofa_plot
```


```{r calibration: multiple curves: APACHE score}

#Univariate APACHE
mort_apache <- glm(hosp_death ~ APACHE, family=binomial(link = 'logit'), data=imgs)
pred_apache <- predict(mort_apache, type=c("response"))
roccurve4 <- roc(imgs$hosp_death ~ pred_apache)
roc4 <- ggroc(roccurve4)
auc(roccurve4)

#CXR + APACHE
mort_cxr_apache <- glm(hosp_death ~ Total+APACHE, family=binomial(link = 'logit'), data=imgs)
pred_cxr_apache <- predict(mort_cxr_apache, type=c("response"))
roccurve5 <- roc(imgs$hosp_death ~ pred_cxr_apache)
roc5 <- ggroc(roccurve5)
auc(roccurve5)


#CXR & APACHE
apache_plot <- ggroc(list(CXR=roccurve, APACHE=roccurve4, CXRAPACHE=roccurve5), legacy.axes = T) + theme_linedraw() + 
  geom_segment(aes(x=0,xend=1,y=0,yend=1), color="darkgray", linetype="dashed") +
  scale_color_manual(values=c("royalblue", "springgreen4", "cyan2"), labels=c("CXR (AUC 0.64)", "APACHE (AUC 0.65)", "CXR+APACHE (AUC 0.70)")) +
  theme(legend.title = element_blank()) + theme(legend.position = c(0.65,0.2)) 

apache_plot
```

```{r two plot arrangement}
grid.arrange(sofa_plot, apache_plot, ncol=2)
```

```{r}

```





