---
title: "subgroup"
author: "Stefanie Mason"
date: "8/20/2019"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE}
library(readxl)
library(dplyr)
library(ggplot2)
library(survival)
library(survminer)
library(QuantPsyc)
library(gridExtra)
library(clinfun)

knitr::opts_chunk$set(message = FALSE)
```


```{r load data, echo=FALSE}
#Load data
outcomes <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "Outcomes", range = cell_cols(1:27))
imgs <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "Imaging", range = cell_cols(1:11))
med_hist <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "baseline_data", range = cell_cols(1:32))
```

```{r more prep}
#RWarngle data
med_hist <- med_hist %>% dplyr::select(subj_id, heart_disease___2, copd) %>% mutate(chf = as.factor(heart_disease___2), copd = as.factor(copd)) %>% dplyr::select(-heart_disease___2) %>% dplyr::rename(Subject_ID = subj_id) 

outcomes <- outcomes %>% mutate(non_white = as.factor(ifelse(Race == "White, non-Hispanic origin", 0, 1)), hosp_death = as.factor(ifelse(DC_coded == 0 | DC_coded == 1, 1, 0)), Immsupp = as.factor(Immsupp), Male = as.factor(Male)) %>% left_join(med_hist, by = "Subject_ID")

imgs <- imgs %>% dplyr::select(-day_3_cxr, -day_5_cxr) %>% filter(admit_cxr == 1) %>% left_join(outcomes, by = "Subject_ID") %>% filter(Final_Dx != "Control") 

#Numerics to factor
imgs$mort28d <- as.factor(imgs$mort28d)
imgs$mort60d <- as.factor(imgs$mort60d)
rm(outcomes)
rm(med_hist)
```

```{r create surivival data}
refdate <- as.Date("2018-09-15")
#Create variables with survival (in days) and a binary indicating censored status
imgs <- mutate(imgs, survival = ifelse(is.na(date_death) == TRUE, as.numeric(difftime(refdate, ICU_admit, units='days')), as.numeric(difftime(date_death, ICU_admit, units='days')))) %>% mutate(censor = ifelse(is.na(date_death) == TRUE, 0, 1))
```

```{r create quartiles}
#create quartiles
imgs <- imgs %>% mutate(quartile = ntile(Total,4)) 
imgs$quartile <- as.factor(imgs$quartile)
```

```{r in hosp controlling for copd/chf}
#In-hospital mortality, entire cohort
hosp_mort_phx <- glm(hosp_death ~ Total+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=imgs)
summary(hosp_mort)

cbind(OR = exp(coef(hosp_mort_phx)),
      exp(confint(hosp_mort_phx)),
      p = coef(summary(hosp_mort_phx))[,4])
```

```{r in-hosp non ARDS}
hosp_mort_non <- imgs %>% filter(Final_Dx != "ARDS" & Final_Dx != "Sepsis/ARDS") %>% 
  glm(hosp_death ~ Total+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=.)
summary(hosp_mort_non)

cbind(OR = exp(coef(hosp_mort_non)),
      exp(confint(hosp_mort_non)),
      p = coef(summary(hosp_mort_non))[,4])
```

```{r in hosp ARDS only}
hosp_mort_ards <- imgs %>% filter(Final_Dx == "ARDS" | Final_Dx == "Sepsis/ARDS") %>% 
  glm(hosp_death ~ Total+Male+Age+Immsupp+APACHE+non_white+copd+chf, family=binomial(link='logit'), data=.)
summary(hosp_mort_ards)

cbind(OR = exp(coef(hosp_mort_ards)),
      exp(confint(hosp_mort_ards)),
      p = coef(summary(hosp_mort_ards))[,4])
```

```{r in those with hx of CHF}
hosp_mort_chf <- imgs %>% filter(chf == 1) %>% 
  glm(hosp_death ~ Total+APACHE, family=binomial(link='logit'), data=.)
summary(hosp_mort_chf)
```

```{r in those with hx of COPD}
hosp_mort_copd <- imgs %>% filter(copd == 1) %>% 
  glm(hosp_death ~ Total+APACHE, family=binomial(link='logit'), data=.)
summary(hosp_mort_copd)
```


#OSH scans

```{r}
imgs %>% dplyr::select(Subject_ID, intub, ICU_admit, ICU_days, Hosp_admit, Hosp_days) %>% filter(Hosp_admit > ICU_admit)
```

```{r}
imgs %>% dplyr::select(Subject_ID, intub, ICU_admit, ICU_days, Hosp_admit, Hosp_days) %>% filter(intub < Hosp_admit)
```




