---
title: "Table1"
author: "S. Mason"
date: "10/4/2018"
output:
  html_document:
    code_folding: hide
    theme: flatly
    toc: yes
    toc_depth: 2
    toc_floating: yes
  word_document:
    toc: yes
    toc_depth: '2'
---

```{r setup, echo=FALSE, message=FALSE}
library(readxl)
library(tidyverse)
library(table1)
library(tableone)
library(officer)
```
```{r load data, message=FALSE, echo=FALSE}
#Load data
outcomes <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "Outcomes", range = cell_cols(1:27))
imgs <- read_excel("~/Documents/ROCIanalysis/ROCI_101918.xlsx", sheet = "Imaging", range = cell_cols(1:11))

#RWarngle data
outcomes <- outcomes %>% mutate(non_white = as.factor(ifelse(Race == "White, non-Hispanic origin", 0, 1)), hosp_death = as.factor(ifelse(DC_coded == 0 | DC_coded == 1, 1, 0)), Immsupp = as.factor(Immsupp), Male = as.factor(Male))

imgs <- imgs %>% dplyr::select(-day_3_cxr, -day_5_cxr) %>% filter(admit_cxr == 1) %>% left_join(outcomes, by = "Subject_ID") %>% filter(Final_Dx != "Control") 

#Numerics to factor
imgs$mort28d <- as.factor(imgs$mort28d)
imgs$mort60d <- as.factor(imgs$mort60d)

```
```{r}
#temp <- images %>% filter(admit_cxr == 1) %>% left_join(outcomes, by="Subject_ID") %>% filter(Final_Dx != "Control")
```

```{r}
#Creates one dataset of outcomes and scores for subjects with a CXR from MICU admit
demos <- imgs %>%  mutate(on_MV = ifelse(days_MV==0, 0, 1))
```
```{r factors}
#Numerics to factor
demos$Male <- factor(demos$Male, levels=c(1,0), labels=c("Male", "Female"))
demos$non_white <- factor(demos$non_white, levels=c(1,0), labels=c("Non-caucasian", "Caucasian"))
demos$Immsupp <- factor(demos$Immsupp, levels = c(1,0), labels = c("Yes", "No"))
demos$hosp_death <- factor(demos$hosp_death, levels = c(1,0), labels = c("Died", "Survived to discharge"))
demos$mort28d <- factor(demos$mort28d, levels = c(1,0), labels = c("Died", "Survived >28 days"))
demos$on_MV <- factor(demos$on_MV, levels = c(1,0), labels = c("Intubated", "no IPPV"))


colnames(demos)
```

```{r table1}
label(demos$Age) <- "Age"
label(demos$Male) <- "Male"
label(demos$non_white) <- "Caucasian"
label(demos$Immsupp) <-"Immunosuppressed"
label(demos$APACHE) <- "APACHE II"
label(demos$on_MV) <- "Intubated"
label(demos$hosp_death) <- "In hospital mortality"
label(demos$mort28d) <- "28-day mortality"

units(demos$Age) <- "yrs"

Tbl1 <- table1(~ Age + Male + non_white + Immsupp + APACHE + on_MV + hosp_death + mort28d, data=demos)

Tbl1

```

```{r}
labels <- list(
  variables=list(Age="Age (yrs)", Male="Male", non_white="Caucasian", Immsupp="Immunosuppressed", APACHE="APACHE", on_MV="Intubated", hosp_death="In hospital mortality", mort28d="28 day mortality"))

strata <- c(list(Overall=demos))

my.render.cont <- function(x) {
  with(stats.apply.rounding(stats.default(x), digits=2), c("", "Mean (SD)" = sprintf("%s (&plusmn; %s)", MEAN, SD)))
}

my.render.cat <- function(x) {
  c("", sapply(stats.default(x), function(y) with(y, sprintf("%d (%0.0f %%)", FREQ, PCT))))
}

table1(strata, labels, render.continuous=my.render.cont, render.categorical=my.render.cat)
```

```{r}
vars=c("Age", "Male", "non_white", "Immsupp", "APACHE", "on_MV", "hosp_death", "mort_28d")

#Tbl1 <- CreateTableOne(vars = vars, data = demos)
```

```{r}
shapiro.test(imgs$Age)
shapiro.test(imgs$APACHE)
```


